cc_test(
  name = "tests",
  srcs  = glob(["**/*.cpp","**/*.h"]),
  deps = [
      "//src/lib:MQUtilityLib",
      "@googletest//:gtest_main"
  ]
  # copts =["-I /Users/Zied/Projects/STAR-MQ-Utility/gtest/internal/"
  #        ,"-I /Users/Zied/Projects/STAR-MQ-Utility/gtest/"],
  # linkopts = ["//gtest/libgtest_main.a","//gtest/libgtest.a"]
)
